//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int id { get; set; }
        public string lang_name { get; set; }
        public Nullable<int> profiency_id { get; set; }
        public Nullable<int> test_type_id { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual profiency profiency { get; set; }
        public virtual Test_type Test_type { get; set; }
    }
}
