//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lastest_post
    {
        public int id { get; set; }
        public string photo { get; set; }
        public string title { get; set; }
        public Nullable<int> category_id { get; set; }
        public string description { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
