//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplyEntities3 : DbContext
    {
        public ApplyEntities3()
            : base("name=ApplyEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acount_plan> acount_plan { get; set; }
        public virtual DbSet<Acount_value> Acount_value { get; set; }
        public virtual DbSet<Adm_User> Adm_User { get; set; }
        public virtual DbSet<Bugdet> Bugdet { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<citizinship> citizinship { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<degree_level> degree_level { get; set; }
        public virtual DbSet<Faq> Faq { get; set; }
        public virtual DbSet<Journey> Journey { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<lastest_post> lastest_post { get; set; }
        public virtual DbSet<Pay_method> Pay_method { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<post_galery> post_galery { get; set; }
        public virtual DbSet<profiency> profiency { get; set; }
        public virtual DbSet<rank_to_rait> rank_to_rait { get; set; }
        public virtual DbSet<ranking_rating> ranking_rating { get; set; }
        public virtual DbSet<referance> referance { get; set; }
        public virtual DbSet<study_field> study_field { get; set; }
        public virtual DbSet<study_field_uni> study_field_uni { get; set; }
        public virtual DbSet<study_program> study_program { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Test_type> Test_type { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<uni_date> uni_date { get; set; }
        public virtual DbSet<Uni_detail> Uni_detail { get; set; }
        public virtual DbSet<Uni_fact> Uni_fact { get; set; }
        public virtual DbSet<Uni_ranking> Uni_ranking { get; set; }
        public virtual DbSet<University> University { get; set; }
        public virtual DbSet<user_finance_plan> user_finance_plan { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsrLevel> UsrLevel { get; set; }
        public virtual DbSet<Type_blog> Type_blog { get; set; }
        public virtual DbSet<SameDate> SameDate { get; set; }
    }
}
