//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string card_name { get; set; }
        public Nullable<int> card_number { get; set; }
        public Nullable<int> cvn_number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> pay_method_id { get; set; }
    
        public virtual Pay_method Pay_method { get; set; }
        public virtual Users Users { get; set; }
    }
}
