//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_galery
    {
        public int id { get; set; }
        public string title { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public Nullable<int> type_id { get; set; }
    
        public virtual Type_blog Type_blog { get; set; }
    }
}
