//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class referance
    {
        public int id { get; set; }
        public string ref_firstname { get; set; }
        public string ref_lastname { get; set; }
        public string ref_email { get; set; }
        public string ref_Phone { get; set; }
        public string ref_relation { get; set; }
        public string essasy { get; set; }
    }
}
