//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SameDate
    {
        public int id { get; set; }
        public string logo { get; set; }
        public string facebook { get; set; }
        public string linkedin { get; set; }
        public string twitter { get; set; }
        public string google { get; set; }
        public string instagram { get; set; }
        public string phone { get; set; }
        public string location { get; set; }
    }
}
