//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public University()
        {
            this.study_field_uni = new HashSet<study_field_uni>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> detail_id { get; set; }
        public Nullable<int> fact_id { get; set; }
        public Nullable<int> rank_to_rate_id { get; set; }
        public Nullable<int> uni_date_id { get; set; }
    
        public virtual rank_to_rait rank_to_rait { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<study_field_uni> study_field_uni { get; set; }
        public virtual uni_date uni_date { get; set; }
        public virtual Uni_detail Uni_detail { get; set; }
        public virtual Uni_fact Uni_fact { get; set; }
    }
}
